_book/src/Automobile/Automobile/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('',include('home.urls')),
    path('admin/', admin.site.urls),
    path('home/', include('home.urls')),
]

_book/src/Automobile/home/urls.py
from django.urls import path
from . import views

urlpatterns = [
	path('', views.home, name='home'),
	path('search1', views.search1, name='search1'),
	path('search2', views.search2, name='search2'),
	path('search3', views.search3, name='search3'),
	path('search4', views.search4, name='search4'),
	path('search5', views.search5, name='search5'),
]

_book/src/Automobile/home/models.py
from django.db import models
import uuid

class Customer(models.Model):
    GENDER_CHOICES = (
        ('1', '男'),
        ('2', '女'),
		('3', '其他'),
    )
    CID = models.CharField(max_length = 36, primary_key = True, default = uuid.uuid4, editable = False)
    C_name = models.CharField(verbose_name = '客戶名稱', max_length = 128, unique = True)
    address = models.TextField(verbose_name = '客戶地址', blank = True)
    phone = models.CharField(verbose_name = '客戶電話', max_length = 16, blank = True)
    gender = models.CharField(verbose_name = '客戶性別', max_length = 3, choices = GENDER_CHOICES, default = '3')
    annual_income = models.FloatField(verbose_name = '客戶年收入', blank = True)
	
    def __str__(self):
      return '%s' % (self.C_name)

class Dealer(models.Model):
    DID = models.CharField(max_length = 36, primary_key = True, default = uuid.uuid4, editable = False)
    D_name = models.CharField(verbose_name = '經銷商名稱', max_length = 128)

    def __str__(self):
	    	return '%s' % (self.D_name)

class Brand(models.Model):
    B_name = models.CharField(verbose_name = '品牌名稱', max_length = 128, primary_key = True)

    def __str__(self):
	    	return '%s' % (self.B_name)

class Model(models.Model):
    STYLE_CHOICES = (
        ('1', 'SUV'),
        ('2', '4-door'),
        ('3', 'wagon')
    )
    MID = models.CharField(max_length = 36, primary_key = True, default = uuid.uuid4, editable = False)
    M_name = models.CharField(verbose_name = '車型名稱', max_length = 128)
    body_style = models.CharField(verbose_name = '車體風格',max_length = 3, choices = STYLE_CHOICES,)
    B_name = models.ForeignKey(Brand, on_delete = models.CASCADE)

    def __str__(self):
		    return '%s' % (self.M_name)

class Supplier(models.Model):
    SID = models.CharField(verbose_name = '供應商名稱', max_length = 128, primary_key = True)

    def __str__(self):
	    	return '%s' % (self.SID)

class Manufacturer(models.Model):
    MFID = models.CharField(verbose_name = '製造商名稱', max_length = 128, primary_key = True)

    def __str__(self):
	    	return '%s' % (self.MFID)

class Engine(models.Model):
    EID = models.CharField(max_length = 36, primary_key = True, default = uuid.uuid4, editable = False)
    SID = models.ForeignKey(Supplier, on_delete = models.SET_NULL, null=True)
    MFID = models.ForeignKey(Manufacturer, on_delete = models.SET_NULL, null=True)
    date = models.DateField(verbose_name = '製造日期')

    def __str__(self):
	    	return '%s' % (self.EID)

class Transmission(models.Model):
    TID = models.CharField(max_length = 36, primary_key = True, default = uuid.uuid4, editable = False)
    SID = models.ForeignKey(Supplier, on_delete = models.SET_NULL, null=True)
    MFID = models.ForeignKey(Manufacturer, on_delete = models.SET_NULL, null=True)
    date = models.DateField(verbose_name = '製造日期')

    def __str__(self):
	    	return '%s' % (self.TID)

class Option(models.Model):
    OID = models.CharField(max_length = 36, primary_key = True, default = uuid.uuid4, editable = False)
    color = models.CharField(verbose_name = '顏色', max_length = 128)
    engine = models.ForeignKey(Engine, on_delete = models.SET_NULL, null=True)
    transmission = models.ForeignKey(Transmission, on_delete = models.SET_NULL, null=True)
    MID = models.ForeignKey(Model, on_delete = models.SET_NULL, null=True)

    def __str__(self):
        return '%s' % self.color

class Vehicle(models.Model):
    VIN = models.CharField(max_length = 36, primary_key = True, default = uuid.uuid4, editable = False)
    OID = models.ForeignKey(Option, on_delete = models.SET_NULL, null=True)

    def __str__(self):
		    return '%s' % (self.VIN)

class Sale(models.Model):
    VIN = models.ForeignKey(Vehicle, on_delete = models.CASCADE)
    CID = models.ForeignKey(Customer, on_delete = models.SET_NULL, blank = True, null=True)
    DID = models.ForeignKey(Dealer, on_delete = models.SET_NULL, null=True)
    date_purchase = models.DateField(verbose_name = '進貨日期')
    date_sold = models.DateField(verbose_name = '出售日期', blank = True, null = True)
    price = models.FloatField(verbose_name = '價錢', blank = True, null = True)

    def __str__(self):
		    return '進貨：%s 賣出：%s' % (self.date_purchase, self.date_sold)

class Produce(models.Model):
    VIN = models.ForeignKey(Vehicle, on_delete = models.CASCADE)
    MFID = models.ForeignKey(Manufacturer, on_delete = models.SET_NULL, null=True)
    date = models.DateField(verbose_name = '組裝日期')

    def __str__(self):
    		return '%s %s' % (self.VIN, self.date)

_book/src/Automobile/home/forms.py
from django import forms
from home.models import *
from django.forms import CharField, ModelMultipleChoiceField, ModelChoiceField, DateField


class Act1Form(forms.Form):
    # PART_CHOICES = (
    #     ('engine', 'engine'),
    #     ('transmission', 'transmission'),
    # )
    # part = forms.ChoiceField(label = '零件', choices = PART_CHOICES)
    supplier = forms.ModelChoiceField(label = '供應商', queryset = Supplier.objects.all())
    sDate = forms.DateField(widget = forms.SelectDateWidget())
    fDate = forms.DateField(widget = forms.SelectDateWidget())

_book/src/Automobile/home/views.py
from django.shortcuts import render
from django.http import HttpResponse
from django import forms
from .models import *
from .forms import *
import datetime

def home(request):
	return render(request, 'home/home.html', locals())

def search1(request):
	# first: 零件壞掉
	# input: supplier_name, two dates, broken_part
	# return: VIN of that car, customer who brought it.
	act1form = Act1Form(request.POST)
	if act1form.is_valid():
		supplier_name = act1form.cleaned_data['supplier']
		act1form.supplier = act1form.cleaned_data['supplier']
		start_date = act1form.cleaned_data['sDate']
		act1form.sDate = act1form.cleaned_data['sDate']
		end_date = act1form.cleaned_data['fDate']
		act1form.fDate = act1form.cleaned_data['fDate']
		broken_part = request.POST.get('part')
		# broken_part = act1form.cleaned_data['part']
		# act1form.part = act1form.cleaned_data['part']

	if act1form.is_valid() and broken_part == 'transmission':
		transmission = Transmission.objects.filter(
			SID = Supplier.objects.get(SID = supplier_name)
			).filter(
			date__lte = end_date
			).filter(
			date__gte = start_date
			)
		option_list = Option.objects.none()
		for item in transmission:
			option_list = option_list.union(Option.objects.filter(transmission = item))
		VIN_list = Vehicle.objects.none()
		for item in option_list:
			VIN_list = VIN_list.union(Vehicle.objects.filter(OID = item))
		sale_list = Sale.objects.none()
		for item in VIN_list:
			sale_list = sale_list.union(Sale.objects.filter(VIN = item, date_sold__isnull = False))
		customer_list = [sale.CID for sale in sale_list]
		return render(request, 'home/search1.html', locals())
	if act1form.is_valid() and broken_part == 'engine':
		engine = Engine.objects.filter(
			SID = Supplier.objects.get(SID = supplier_name)
			).filter(
			date__lte = end_date
			).filter(
			date__gte = start_date
			)
		option_list = Option.objects.none()
		for item in engine:
			option_list = option_list.union(Option.objects.filter(engine = item))
		VIN_list = Vehicle.objects.none()
		for item in option_list:
			VIN_list = VIN_list.union(Vehicle.objects.filter(OID = item))
		sale_list = Sale.objects.none()
		for item in VIN_list:
			sale_list = sale_list.union(Sale.objects.filter(VIN = item, date_sold__isnull = False))
		customer_list = [sale.CID for sale in sale_list]
		# raise Exception()
		return render(request, 'home/search1.html', locals())		

	
	# second: best dealer
	# sold the most in the part

	# third: top n brand

	# forth: which month sell best
	# input: car_style

	# 5th: worst dealer
	return render(request, 'home/search1.html', locals())

def search2(request):
	today = datetime.date.today()
	dealer_list = Dealer.objects.all()
	dealer_dollar = {}
	if request.POST.get('dealerN'):
		number = request.POST.get('dealerN')
		for item in dealer_list:
			sale_list = Sale.objects.filter(DID = item, date_sold__range = [today - datetime.timedelta(days=365),today])
			dollar_list = sale_list.values_list('price', flat=True)
			sum_dollar = sum(dollar_list)
			dealer_dollar.update({item : sum_dollar})
		dealer_rank = [ item for item in sorted(dealer_dollar.items(), key=lambda d: d[1], reverse=True)]
		dealer_rank = dealer_rank[:int(number)]
	return render(request, 'home/search2.html', locals())

def search3(request):
	today = datetime.date.today()
	if request.POST.get('brandN'):
		number = request.POST.get('brandN')
		brand_list = Brand.objects.all()
		brand_sale = {}
		for brand in brand_list:
			model_list = Model.objects.none()
			model_list = Model.objects.filter(B_name = brand)
			option_list = Option.objects.none()
			for item in model_list:
				option_list = option_list.union(Option.objects.filter(MID = item))
			VIN_list = Vehicle.objects.none()
			for item in option_list:
				VIN_list = VIN_list.union(Vehicle.objects.filter(OID = item))
			sale_list = Sale.objects.none()
			for item in VIN_list:
				sale_list = sale_list.union(Sale.objects.filter(VIN = item, date_sold__range = [today - datetime.timedelta(days=365),today]))
			brand_sale.update({brand : sale_list.count()})
		brand_rank = [ item for item in sorted(brand_sale.items(), key=lambda d: d[1], reverse=True)]
		brand_rank = brand_rank[:int(number)]

	return render(request, 'home/search3.html', locals())

def search4(request):
	bodystyle = request.POST.get('bodystyle')
	model_list = Model.objects.filter(body_style = bodystyle)
	option_list = Option.objects.none()
	for item in model_list:
		option_list = option_list.union(Option.objects.filter(MID = item))
	VIN_list = Vehicle.objects.none()
	for item in option_list:
		VIN_list = VIN_list.union(Vehicle.objects.filter(OID = item))
	month_sale = []
	for month in range(1,13):
		sale_list = Sale.objects.none()
		for item in VIN_list:
			sale_list = sale_list.union(Sale.objects.filter(VIN = item, date_sold__month = month))
		n = sale_list.count()
		month_sale.append(n)
	sum_n = sum(month_sale) 
	best_month = month_sale.index(max(month_sale))+1
	
	return render(request, 'home/search4.html', locals())

def search5(request):
	number = request.POST.get('badD')
	today = datetime.date.today()
	dealer_list = Dealer.objects.all()
	bad_dealer = {}
	if request.POST.get('badD'):
		for dealer in dealer_list:
			sale_list = Sale.objects.filter(DID = dealer)
			time_list = []
			for item in sale_list:
				if item.date_sold:
					time_list.append((item.date_sold-item.date_purchase).days)
				else:
					time_list.append((today - item.date_purchase).days)
			bad_dealer.update({dealer : sum(time_list)/len(time_list)})
		worst_dealer = [ item for item in sorted(bad_dealer.items(), key=lambda d: d[1], reverse=True)]
		worst_dealer = worst_dealer[:int(number)]
	return render(request, 'home/search5.html', locals())

_book/src/Automobile/home/templates/home/home.html
<html>

<head>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
    <TITLE>ALTOMOBILE</TITLE>
    <link href="https://fonts.googleapis.com/css?family=Noto+Sans+TC&amp;display=swap" rel="stylesheet" />
    <style>
        body {
            font-family: 'Noto Sans TC', '微軟正黑體', 'Microsoft JhengHei', sans-serif;
            letter-spacing: 3px;
        }

        td {
            border: 1px solid #333;
            padding: 10px;
        }
    </style>
</head>

<body>
    <button onclick="location.href='search1'">零件壞掉</button>
    <button onclick="location.href='search2'">最佳Dealer</button>
    <button onclick="location.href='search3'">最佳Brand</button>
    <button onclick="location.href='search4'">賣最好月</button>
    <button onclick="location.href='search5'">最廢Dealer</button>
    {% block content %}
    {% endblock %}
</body>

<footer>

</footer>

</html>

_book/src/Automobile/home/templates/home/search1.html
{% extends "home/home.html" %}
{% block content %}
<div style="border-top:1px dashed #cccccc;height: 1px;overflow:hidden;margin:10px 0px;"></div>

<form action="/search1" method="POST">
    {% csrf_token %}
    <div>
        Detail:
        <p style="margin: 10px 20px;">發現<b>供應商</b>在<b>某段期間</b>製造的<b>零件</b>有瑕疵，
            <br>查詢每輛含有該零件的車子及購買該車的顧客。</p>
    </div>
    <div style="font-size: 14px;margin: 20px;">
        有瑕疵零件:<select name="part">
            <option value="">----------</option>
            <option value="engine">engine</option>
            <option value="transmission">transmission</option>
            </select> <br>
        供應商:{{ act1form.supplier }} <br>
        製造日期:{{ act1form.sDate }} ~ {{ act1form.fDate }}
    </div>
    <button type="submit" style="margin: 10px 20px;">查詢</button>
</form>

{% if request.POST %}
<p style="margin: 10px 20px;"><b>{{ supplier_name }}</b>在<b>{{ start_date }}~{{ end_date }}</b>製造的<b>{{ broken_part }}</b>有瑕疵</p>

<table style="text-align: center;border: 1px solid black;position: relative;left: 20px;">
    <tr>
        <td style="background-color: #333; color: #fff;">VIN</td>
        <td style="background-color: #333; color: #fff;">CUSTOMER</td>
    </tr>
    {% for sale in sale_list %}
    <tr>
        <td>{{ sale.VIN }}</td>
        <td>{{ sale.CID }}</td>
    </tr>
    {% endfor %}
</table>

{% endif %}

{% endblock %}

_book/src/Automobile/home/templates/home/search2.html
{% extends "home/home.html" %}
{% block content %}
<div style="border-top:1px dashed #cccccc;height: 1px;overflow:hidden;margin:10px 0px;"></div>

<form action="/search2" method="POST">
    {% csrf_token %}
    <div>
        Detail:
        <p style="margin: 10px 20px;">查詢過去一年<b>最佳經銷商</b>。</p>
    </div>
    <div style="font-size: 14px;margin: 20px;">
        列出前<input name="dealerN" type="number" min="1" width="20px">名經銷商。
    </div>
    <button type="submit" style="margin: 10px 20px;">查詢</button>
</form>

{% if request.POST %}
<h3 style="margin: 10px 20px;">過去一年最佳經銷商</h3>

<table style="text-align: center;border: 1px solid black;position: relative;left: 20px;">
    <tr>
        <td style="background-color: #333; color: #fff;">DEALER</td>
        <td style="background-color: #333; color: #fff;">總銷售額</td>
    </tr>
    {% for item in dealer_rank %}
    <tr>
        <td>{{ item.0 }}</td>
        <td>{{ item.1 }}</td>
    </tr>
    {% endfor %}
</table>
{% endif %}

{% endblock %}

_book/src/Automobile/home/templates/home/search3.html
{% extends "home/home.html" %}
{% block content %}
<div style="border-top:1px dashed #cccccc;height: 1px;overflow:hidden;margin:10px 0px;"></div>

<form action="/search3" method="POST">
    {% csrf_token %}
    <div>
        Detail:
        <p style="margin: 10px 20px;">查詢過去一年<b>優秀的品牌</b>。</p>
    </div>
    <div style="font-size: 14px;margin: 20px;">
        列出前<input name="brandN" type="number" min="1" width="20px">名品牌。
    </div>
    <button type="submit" style="margin: 10px 20px;">查詢</button>
</form>

{% if request.POST %}
<h3 style="margin: 10px 20px;">過去一年最佳品牌</h3>

<table style="text-align: center;border: 1px solid black;position: relative;left: 20px;">
    <tr>
        <td style="background-color: #333; color: #fff;">DEALER</td>
        <td style="background-color: #333; color: #fff;">總銷售額</td>
    </tr>
    {% for item in brand_rank %}
    <tr>
        <td>{{ item.0 }}</td>
        <td>{{ item.1 }}</td>
    </tr>
    {% endfor %}
</table>
{% endif %}

{% endblock %}

_book/src/Automobile/home/templates/home/search4.html
{% extends "home/home.html" %}
{% block content %}
<div style="border-top:1px dashed #cccccc;height: 1px;overflow:hidden;margin:10px 0px;"></div>

<form action="/search4" method="POST">
    {% csrf_token %}
    <div>
        Detail:
        <p style="margin: 10px 20px;">查詢<b>車體風格</b>最暢銷的<b>月份</b>。</p>
    </div>
    <div style="font-size: 14px;margin: 20px;">
        車體風格:<select name="bodystyle">
            <option value="">--------</option>
            <option value="1">SUV</option>
            <option value="2">4-door</option>
            <option value="3">wagon</option>
        </select> <br>
    </div>
    <button type="submit" style="margin: 10px 20px;">查詢</button>
</form>
{% if sum_n == 0 and bodystyle%}
<h2 style="margin: 10px 20px;">尚未有 {{model_list.0.get_body_style_display}} 售出。</h2>
{% elif bodystyle %}
<h2 style="margin: 10px 20px;">{{model_list.0.get_body_style_display}}在 {{best_month}}月 最暢銷。</h2>
{% endif %}

{% endblock %}

_book/src/Automobile/home/templates/home/search5.html
{% extends "home/home.html" %}
{% block content %}
<div style="border-top:1px dashed #cccccc;height: 1px;overflow:hidden;margin:10px 0px;"></div>

<form action="/search5" method="POST">
    {% csrf_token %}
    <div>
        Detail:
        <p style="margin: 10px 20px;">查詢將車輛放在庫存平均時間最長的<b>最廢經銷商</b>。</p>
    </div>
    <div style="font-size: 14px;margin: 20px;">
        列出前<input name="badD" type="number" min="1" width="20px">名差勁經銷商。
    </div>
    <button type="submit" style="margin: 10px 20px;">查詢</button>
</form>

{% if request.POST %}
<h3 style="margin: 10px 20px;">差勁的經銷商們</h3>

<table style="text-align: center;border: 1px solid black;position: relative;left: 20px;">
    <tr>
        <td style="background-color: #333; color: #fff;">DEALER</td>
        <td style="background-color: #333; color: #fff;">車輛平均庫存天數</td>
    </tr>
    {% for item in worst_dealer %}
    <tr>
        <td>{{ item.0 }}</td>
        <td>{{ item.1 }}</td>
    </tr>
    {% endfor %}
</table>
{% endif %}

{% endblock %}